name: Build and Deploy

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io \
            -u "${{ secrets.GHCR_USERNAME }}" \
            --password-stdin

      - name: Build Docker Image
        run: |
          docker build \
            -t ghcr.io/${{ secrets.GHCR_USERNAME }}/uptime-monitor:${{ github.sha }} \
            .

      - name: Push Docker Image
        run: |
          docker push \
            ghcr.io/${{ secrets.GHCR_USERNAME }}/uptime-monitor:${{ github.sha }}

      - name: Update GitOps Repository
        env:
          GITOPS_PAT: ${{ secrets.GITOPS_PAT }}
        run: |
          git clone https://sirajmoideen:${GITOPS_PAT}@github.com/sirajmoideen/uptime-monitor-gitops.git

          cd uptime-monitor-gitops

          if [ "${GITHUB_REF_NAME}" = "dev" ]; then
            FILE=environments/dev/values.yaml
          else
            FILE=environments/prod/values.yaml
          fi

          sed -i "/tag:/c\  tag: ${GITHUB_SHA}" "$FILE"

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add "$FILE"
          git commit -m "Update image tag to ${GITHUB_SHA}" || true

          git push origin main